<?php

namespace Proxies\__CG__\Travel\TravelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transport extends \Travel\TravelBundle\Entity\Transport implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'id', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'transit', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'comission', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'dateTransport', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'client', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'camion'];
        }

        return ['__isInitialized__', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'id', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'transit', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'comission', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'dateTransport', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'client', '' . "\0" . 'Travel\\TravelBundle\\Entity\\Transport' . "\0" . 'camion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Transport $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransit($transit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransit', [$transit]);

        return parent::setTransit($transit);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransit', []);

        return parent::getTransit();
    }

    /**
     * {@inheritDoc}
     */
    public function setComission($comission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComission', [$comission]);

        return parent::setComission($comission);
    }

    /**
     * {@inheritDoc}
     */
    public function getComission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComission', []);

        return parent::getComission();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateTransport($dateTransport)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateTransport', [$dateTransport]);

        return parent::setDateTransport($dateTransport);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateTransport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateTransport', []);

        return parent::getDateTransport();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(\Travel\TravelBundle\Entity\Client $client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setCamion(\Travel\TravelBundle\Entity\Camion $camion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCamion', [$camion]);

        return parent::setCamion($camion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCamion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCamion', []);

        return parent::getCamion();
    }

}
